### ISSUE TITLE
Tslint4.0 Change api and exception raised

### ISSUE THREAD

**Issue by heavenshell** [buzinas/tslint-eslint-rules#137]
When running with Tslint4.0, exception raised.

```
$ tslint -c tslint.json tests/*.ts
no-unused-variable is deprecated. Use the compiler options --noUnusedParameters and --noUnusedLocals instead.
module.js:471
    throw err;
    ^

Error: Cannot find module 'tslint/lib/lint'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path/to/my-tslint-config/node_modules/tslint-eslint-rules/dist/rules/noConstantConditionRule.js:8:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```

See https://github.com/palantir/tslint/pull/1720

https://github.com/buzinas/tslint-eslint-rules/search?utf8=%E2%9C%93&q=tslint%2Flib%2Flint
I think these should be change.

**Comment by jmlopez-rod** [comment]
I'm working on it but I won't be able to do the update until this is done: https://github.com/panuhorsmalahti/gulp-tslint/issues/90

**Comment by unional** [comment]
That is done. 🌷

**Comment by balassy** [comment]
gulp-tslint 7.0.0 is released, which supports tslint 4.x.
Thanks for fixing this @jmlopez-rod.

**Comment by jmlopez-rod** [comment]
Hi all, v3.0.0 has been released.

**Comment by balassy** [comment]
Thank you!
