### ISSUE TITLE
ter-indent crashes with jsDoc attached to VariableDeclaration

### ISSUE THREAD

**Issue by Kovensky** [buzinas/tslint-eslint-rules#141]
Stack trace:

```
TypeError: Cannot read property 'getText' of undefined
    at IndentWalker.expectedVarIndent (.../node_modules/tslint-eslint-rules/dist/rules/terIndentRule.js:484:50)
    at IndentWalker.checkIndentInVariableDeclarations (.../node_modules/tslint-eslint-rules/dist/rules/terIndentRule.js:608:27)
    at IndentWalker.visitVariableDeclaration (.../node_modules/tslint-eslint-rules/dist/rules/terIndentRule.js:680:14)
    at IndentWalker.SyntaxWalker.visitNode (.../node_modules/tslint/lib/language/walker/syntaxWalker.js:487:22)
...
```

Source code:

```ts
/**
 * Returns the local state from inside the full redux store's state.
 */
const getState = (store: Store) => store.foo
```

Deleting the jsDoc fixes the crash.

**Comment by jmlopez-rod** [comment]
Is there a particular configuration you are using to get this bug? I switch to the master branch but I can't seem to get it. I have a PR ready to address the other bug you submitted but I'd like to get this one in the next release as well. Thanks for the submitting the issues.

**Comment by Kovensky** [comment]
Hm, not sure; I am using the rule with `[ true, 2, { "SwitchCase": 1 } ]`.

Could this be an AST change introduced by typescript? I am running the nightlies.

**Comment by jmlopez-rod** [comment]
Ah, I see it now. I installed the latest they have

```
jmlopez in ~/Workspace/tslint-eslint-rules on master*$ tsc --version
Version 2.2.0-dev.20161128
```

This new version of typescript will break several things. I'll try to see if I can make it work for both versions.

**Comment by jmlopez-rod** [comment]
@Kovensky v3.1.0 has the fixes to this issue and the previous one you reported. Thank you for reporting.
