### ISSUE TITLE
Crash on incorrect JSDoc @return

### ISSUE THREAD

**Issue by Luanre** [buzinas/tslint-eslint-rules#178]
version 3.3.0
If the code has invalid `@return` syntax like this:

```
/**
* @return string
*/
```

it will cause an exception:

```
[Info  - 5:40:13 PM] vscode-tslint: 'Cannot read property 'name' of null' while validating: /Users/Nikolay/workspace/components/src/input.ts stacktrace: TypeError: Cannot read property 'name' of null
    at ValidJsdocWalker.isValidReturnType (/Users/Nikolay/workspace/components/node_modules/tslint-eslint-rules/dist/rules/validJsdocRule.js:130:24)
    at ValidJsdocWalker.checkJSDoc (/Users/Nikolay/workspace/components/node_modules/tslint-eslint-rules/dist/rules/validJsdocRule.js:211:35)
    at ValidJsdocWalker.visitFunctionDeclaration (//Users/Nikolay/workspace/components/node_modules/tslint-eslint-rules/dist/rules/validJsdocRule.js:82:14)
    at ValidJsdocWalker.SyntaxWalker.visitNode (/Users/Nikolay/workspace/components/node_modules/tslint/lib/language/walker/syntaxWalker.js:315:22)
```

It would be nice to have warning that JSDoc has incorrect format.

**Comment by jmlopez-rod** [comment]
Thanks, just confirmed it is also present in version `3.0.0` (the one). This is the bad guy:

```
return tag.type.name === 'void' || tag.type.type === 'UndefinedLiteral';
```
