### ISSUE TITLE
 Invalid "extends" configuration value 

### ISSUE THREAD

**Issue by mikeumus** [buzinas/tslint-eslint-rules#230]
``` 
$ npm run lint

> bloomberg-ic@1.0.0 lint C:\home\ng2\cis-dashboard\web-api\frontend
> ng lint --format stylish

Failed to load C:\home\ng2\cis-dashboard\web-api\frontend\tslint.json: Invalid "extends" configuration value - could no
t require "tslint-eslint-rules". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_toge
ther) for the approximate method TSLint uses to find the referenced configuration file.
Error
    at new FatalError (C:\home\ng2\cis-dashboard\web-api\frontend\node_modules\tslint\lib\error.js:40:23)
    at Object.findConfiguration (C:\home\ng2\cis-dashboard\web-api\frontend\node_modules\tslint\lib\configuration.js:47
:15)
    at files.forEach (C:\home\ng2\cis-dashboard\web-api\frontend\node_modules\@angular\cli\tasks\lint.js:38:50)
    at Array.forEach (native)
    at lintConfigs.map (C:\home\ng2\cis-dashboard\web-api\frontend\node_modules\@angular\cli\tasks\lint.js:32:19)
    at Array.map (native)
    at Class.run (C:\home\ng2\cis-dashboard\web-api\frontend\node_modules\@angular\cli\tasks\lint.js:25:14)
    at Class.run (C:\home\ng2\cis-dashboard\web-api\frontend\node_modules\@angular\cli\commands\lint.js:39:25)
    at Class.<anonymous> (C:\home\ng2\cis-dashboard\web-api\frontend\node_modules\@angular\cli\ember-cli\lib\models\com
mand.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by buzinas** [comment]
It seems that you don't have `tslint-eslint-rules` installed in your project.
