### ISSUE TITLE
--fix fails

### ISSUE THREAD

**Issue by cakeinpanic** [buzinas/tslint-eslint-rules#232]
I'm trying to autofix rule
http://eslint.org/docs/rules/object-curly-spacing, here is its options in `tslint.json`
`"object-curly-spacing": [true, "never"],`

```
tslint --version
4.5.1
tsc --version
Version 2.0.10
```
when i run `tslin --fix`, i got
```
/Users/user/.nvm/versions/node/v6.0.0/lib/node_modules/tslint/lib/runner.js:118
throw error;
^

TypeError: Cannot read property 'apply' of undefined
at /Users/user/.nvm/versions/node/v6.0.0/lib/node_modules/tslint/lib/language/rule/rule.js:28:65
at Array.reduce (native)
at Function.Replacement.applyAll (/Users/user/.nvm/versions/node/v6.0.0/lib/node_modules/tslint/lib/language/rule/rule.js:28:29)
at Function.Fix.applyAll (/Users/user/.nvm/versions/node/v6.0.0/lib/node_modules/tslint/lib/language/rule/rule.js:88:28)
at Linter.lint (/Users/user/.nvm/versions/node/v6.0.0/lib/node_modules/tslint/lib/linter.js:92:41)
at Runner.processFiles (/Users/user/.nvm/versions/node/v6.0.0/lib/node_modules/tslint/lib/runner.js:161:20)
at Runner.run (/Users/user/.nvm/versions/node/v6.0.0/lib/node_modules/tslint/lib/runner.js:110:18)
at Object.<anonymous> (/Users/user/.nvm/versions/node/v6.0.0/lib/node_modules/tslint/lib/tslint-cli.js:139:6)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
```

just linting without `--fix` flag works ok too

If i remove that rule from `tslint.json`, everything lints and fixes great

**Comment by jmlopez-rod** [comment]
You'll need to update to tslint 5. The current state of this project (version 4) was updated to work with tslint 5. Let me know if updating still crashes the process. If so then please provide some sample code.

**Comment by buzinas** [comment]
Closing this since there was no follow up.
